"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'PLACEHOLDER'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# When deploying to Azure App Service, add you <name>.azurewebsites.net 
# domain to ALLOWED_HOSTS; you get an error message if you forget. When you add
# a specific host, you must also add 'localhost' and/or '127.0.0.1' for local
# debugging (which are enabled by default when ALLOWED_HOSTS is empty.)
ALLOWED_HOSTS = [
    #'localhost',
    #'127.0.0.1'
    "http://guardianforge.net/",
    "www.guardianforge.net",
    "guardiansforge.met"
]

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hello',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join( BASE_DIR, 'hello/templates' )],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'guardia2_destiny',
'USER': 'guardia2_ben',
'PASSWORD': 'S)[],mtE0!8V',
'HOST': 'localhost', # Or an IP Address that your DB is hosted on
'PORT': '3306',
}
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# The location where the collectstatic command collects static files from apps.
# A dedicated static file server is typically used in production to serve files
# from this location, rather than relying on the app server to serve those files
# from various locations in the app. Doing so results in better overall performance.
STATIC_ROOT = '/home/guardia2/Web_app/static_collected'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'benfauteux2839@gmail.com'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'pjpfqtfomttiwcpw'  # Replace with your email password
EMAIL_USE_TLS = True
EMAIL_USE_STARTTLS = True
DEFAULT_FROM_EMAIL = 'benfauteux2839@gmail.com'
SERVER_EMAIL = EMAIL_HOST_USER
