# Generated by Django 4.1.7 on 2023-08-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_2',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alumni', models.BooleanField(default=False)),
                ('release_info', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(auto_now=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Company2_list',
            },
        ),
        migrations.CreateModel(
            name='RIT',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alumni', models.BooleanField(default=False)),
                ('release_info', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(auto_now=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'RIT_list',
            },
        ),
    ]
