# Generated by Django 4.1.7 on 2023-08-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_walletpass', '0009_alter_pass_data'),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventTicket',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_walletpass.pass')),
                ('ticket_serial_number', models.CharField(max_length=100)),
                ('pass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.db_model')),
            ],
            bases=('django_walletpass.pass',),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
