# Generated by Django 4.1.7 on 2023-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_db_model_first_name_alter_db_model_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_model',
            name='alumni',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='db_model',
            name='release_info',
            field=models.BooleanField(null=True),
        ),
    ]
