# Generated by Django 4.1.7 on 2023-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_id_entry_id_number_alter_checkintest_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
