# Generated by Django 4.1.7 on 2023-10-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='auto_email_sending_active',
            field=models.BooleanField(),
        ),
    ]
