# Generated by Django 4.1.7 on 2023-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alumni', models.BooleanField(default=False)),
                ('release_info', models.BooleanField(default=False)),
                ('id_number', models.IntegerField()),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Master_list',
            },
        ),
        migrations.DeleteModel(
            name='CheckinTest',
        ),
    ]
