# Generated by Django 4.1.7 on 2023-07-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_rename_id_db_model_entry_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='import_csv',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alumni', models.BooleanField(default=False)),
                ('release_info', models.BooleanField(default=False)),
                ('table_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='db_model',
            name='entry_number',
        ),
        migrations.AlterField(
            model_name='db_model',
            name='id_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
